### ISSUE TITLE
New connect tag for bidirectional Twilio media-streams does not support Google Text-to-speech audio encodings

### ISSUE THREAD

**Issue by msulemannkhan** [twilio/media-streams#56]
I am trying to send back audio generated from google text to speech API. Google text-to-speech API generated audio encoded in MP3, WAV. But Twilio only accepts MULAW, Audio. When I write on stream it generates a loud noise.  

Can you kindly let me know how can I solve this problem?

**Comment by imkhubaibraza** [comment]
@msulemannkhan Google speech to text API returns **LINEAR16 audioencoding**. 
What you need to do is simply convert into **MuLaw audioencoding**. So that, Twilio can understand what are you sending.
- First install wavefile package using  `npm i wavefile`

- copy and paste below code
```const WaveFile = require("wavefile").WaveFile;
const wav = new WaveFile();
wav.fromBuffer(your-audio-content-);
wav.toSampleRate(8000); // converting sampleRate Hertz  into 8000
wav.toMuLaw(); // converting into MuLaw
var buffer_return = Buffer.from(wav.data.samples);
var final_buffer = buffer_return.toString("base64");
```

**Comment by derrickrodrigues** [comment]
@msulemannkhan  The services given in this code works on Dialogflow V2. Is there support for Dialogflow V3 for the same ?

**Comment by MansiSharma98** [comment]
I am also hearing bad static instead of audio. My audio files are .wav
How can I achieve the same using python? @imkhubaibraza 

```
npm i wavefile


const wav = new WaveFile();
wav.fromBuffer(your-audio-content-);
wav.toSampleRate(8000); // converting sampleRate Hertz  into 8000
wav.toMuLaw(); // converting into MuLaw
var buffer_return = Buffer.from(wav.data.samples);
var final_buffer = buffer_return.toString("base64");
```
