### ISSUE TITLE
400 Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.

### ISSUE THREAD

**Issue by LMontull** [twilio/media-streams#72]
After not executing the code for a month, I went back to it and when I'm starting to feed data to the SpeechClientBridge this error happens: 

`grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.OUT_OF_RANGE
	details = "Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time."
	debug_error_string = "{"created":"@1600103598.310142000","description":"Error received from peer ipv6:[2a00:1450:4003:809::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.","grpc_status":11}"
`

I assume this is because google cloud speech is not receiving any audio, but there's audio transmitting on the channel and it's properly connected to the websocket. 

Anyone having this problem? Thanks!

**Comment by sarahcstringer** [comment]
@LMontull thanks for reporting! This should be fixed with PR #84. Let us know if you continue to experience streaming issues.
